import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import multer from 'multer';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { v4 as uuid } from 'uuid';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import Razorpay from 'razorpay';
import { google } from 'googleapis';
import ffmpegPath from 'ffmpeg-static';
import OpenAI from 'openai';

const exec=promisify(execFile), __dirname=path.dirname(fileURLToPath(import.meta.url));
const DATA=path.join(__dirname,'data'), UPLOADS=path.join(DATA,'uploads'), OUTPUTS=path.join(DATA,'outputs');
await fs.mkdir(UPLOADS,{recursive:true}); await fs.mkdir(OUTPUTS,{recursive:true});
const app=express();
const origins=(process.env.FRONTEND_ORIGIN||'https://gowardhan0.github.io').split(',').map(x=>x.trim());
app.use(cors({origin:(o,cb)=>!o||origins.includes(o)?cb(null,true):cb(new Error('Origin not allowed'))}));
app.use(express.json({limit:'2mb'})); app.use('/media',express.static(DATA));
const upload=multer({dest:UPLOADS,limits:{fileSize:Number(process.env.MAX_UPLOAD_BYTES||2000000000)},fileFilter:(_r,f,cb)=>cb(/^video\/(mp4|quicktime|webm|x-matroska)$/.test(f.mimetype)?null:new Error('Only MP4, MOV, WebM or MKV videos are supported.'))});
const jobs=new Map(); const users=new Map(); const oauthStates=new Map();
const openai=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;
const razor=process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET?new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET}):null;
const jwtSecret=process.env.JWT_SECRET||'CHANGE_ME_BEFORE_PRODUCTION';
const base=req=>process.env.PUBLIC_BASE_URL||`${req.protocol}://${req.get('host')}`;
const sign=u=>jwt.sign({sub:u.id,email:u.email,plan:u.plan},jwtSecret,{expiresIn:'30d'});
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),jwtSecret);next()}catch{res.status(401).json({error:'Authentication required'})}}
function enc(v){if(!process.env.APP_ENCRYPTION_KEY||!v)return v;const key=crypto.createHash('sha256').update(process.env.APP_ENCRYPTION_KEY).digest();const iv=crypto.randomBytes(12);const c=crypto.createCipheriv('aes-256-gcm',key,iv);const out=Buffer.concat([c.update(v,'utf8'),c.final()]);return `${iv.toString('base64')}.${c.getAuthTag().toString('base64')}.${out.toString('base64')}`}
function dec(v){try{if(!v||!v.split('.')[2])return v;const [i,t,d]=v.split('.'),key=crypto.createHash('sha256').update(process.env.APP_ENCRYPTION_KEY).digest(),c=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(i,'base64'));c.setAuthTag(Buffer.from(t,'base64'));return Buffer.concat([c.update(Buffer.from(d,'base64')),c.final()]).toString()}catch{return null}}
app.get('/api/health',(_r,res)=>res.json({ok:true,service:'clipforge-api',version:'2.0.0'}));
app.get('/api/config',(_r,res)=>res.json({razorpayKeyId:process.env.RAZORPAY_KEY_ID||null,plans:[{id:'creator',name:'Creator',price:19,currency:'USD'},{id:'pro',name:'Pro',price:49,currency:'USD'},{id:'agency',name:'Agency',price:149,currency:'USD'}]}));
app.post('/api/auth/register',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return res.status(400).json({error:'Use a valid email and an 8+ character password'});if(users.has(email))return res.status(409).json({error:'Account already exists'});const u={id:uuid(),email,password:await bcrypt.hash(password,12),plan:'free',createdAt:new Date().toISOString()};users.set(email,u);res.status(201).json({token:sign(u),user:{id:u.id,email:u.email,plan:u.plan}})});
app.post('/api/auth/login',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),u=users.get(email);if(!u||!(await bcrypt.compare(String(req.body.password||''),u.password)))return res.status(401).json({error:'Invalid email or password'});res.json({token:sign(u),user:{id:u.id,email:u.email,plan:u.plan}})});
app.get('/api/me',auth,(req,res)=>{const u=users.get(req.user.email);res.json({user:u?{id:u.id,email:u.email,plan:u.plan}:req.user})});
app.post('/api/analyze',upload.single('video'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Video file is required'});if(req.body.rightsConfirmed!=='true'){await fs.rm(req.file.path,{force:true});return res.status(400).json({error:'You must confirm ownership or editing permission'});}const id=uuid(),ext=path.extname(req.file.originalname)||'.mp4',source=path.join(UPLOADS,`${id}${ext}`);await fs.rename(req.file.path,source);setJob(id,{id,status:'queued',progress:0,filename:req.file.originalname,owner:req.user?.email||'guest'});res.status(202).json({id,status:'queued'});processJob(id,source,req.body.title||req.file.originalname).catch(e=>setJob(id,{status:'error',error:e.message}));});
app.get('/api/jobs/:id',(req,res)=>{const j=jobs.get(req.params.id);if(!j)return res.status(404).json({error:'Job not found'});res.json(j)});
function setJob(id,p){jobs.set(id,{...(jobs.get(id)||{}),...p,updatedAt:new Date().toISOString()})}
async function probe(f){try{const {stderr}=await exec(ffmpegPath,['-i',f,'-hide_banner'],{maxBuffer:10000000});const m=stderr.match(/Duration:\s*(\d+):(\d+):(\d+(?:\.\d+)?)/);return {duration:m?Number(m[1])*3600+Number(m[2])*60+Number(m[3]):60}}catch(e){const m=(e.stderr||'').match(/Duration:\s*(\d+):(\d+):(\d+(?:\.\d+)?)/);return {duration:m?Number(m[1])*3600+Number(m[2])*60+Number(m[3]):60}}}
async function transcribe(f){if(!openai)return {text:''};const h=await fs.open(f,'r');try{return await openai.audio.transcriptions.create({file:h.createReadStream(),model:process.env.WHISPER_MODEL||'whisper-1',response_format:'verbose_json'})}finally{await h.close().catch(()=>{})}}
async function choose(text,duration,title){const fallback=[{start:Math.max(0,Math.min(duration-45,10)),end:Math.min(duration,55),hook:'The moment that changes how you see this',score:86},{start:Math.max(0,Math.min(duration-40,60)),end:Math.min(duration,100),hook:'Most people miss this part',score:82},{start:Math.max(0,Math.min(duration-35,120)),end:Math.min(duration,155),hook:'Here is the key takeaway',score:79}].filter(x=>x.end>x.start);if(!openai||!text.trim())return fallback;const p=`Select up to 3 standalone Shorts from this transcript. Return JSON object {clips:[{start,end,hook,score,title,description,hashtags}]}. Clips 20-60 seconds; favor hook strength, emotion, usefulness, context completeness and clean endings. Duration ${Math.round(duration)} seconds. Source title: ${title}. Transcript:\n${text.slice(0,45000)}`;try{const r=await openai.chat.completions.create({model:process.env.OPENAI_MODEL||'gpt-4o-mini',temperature:.2,response_format:{type:'json_object'},messages:[{role:'system',content:'You are an expert short-form editor.'},{role:'user',content:p}]});const x=JSON.parse(r.choices[0].message.content);return Array.isArray(x.clips)?x.clips:fallback}catch{return fallback}}
async function renderShort(input,output,start,end){await exec(ffmpegPath,['-y','-ss',String(start),'-i',input,'-t',String(Math.max(5,end-start)),'-vf',"scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2,setsar=1",'-c:v','libx264','-preset',process.env.FFMPEG_PRESET||'veryfast','-crf','22','-c:a','aac','-b:a','128k','-movflags','+faststart',output],{maxBuffer:20000000})}
async function processJob(id,source,title){setJob(id,{status:'processing',progress:10});const m=await probe(source);setJob(id,{duration:m.duration,progress:20});const t=await transcribe(source);setJob(id,{progress:45});const clips=await choose(t.text||'',m.duration,title);const rendered=[];for(let i=0;i<clips.length;i++){const out=path.join(OUTPUTS,`${id}-${i+1}.mp4`);await renderShort(source,out,Number(clips[i].start),Number(clips[i].end));rendered.push({...clips[i],url:`${process.env.PUBLIC_BASE_URL||''}/media/outputs/${path.basename(out)}`});setJob(id,{progress:55+Math.round((i+1)/clips.length*40)})}setJob(id,{status:'complete',progress:100,clips:rendered})}
app.post('/api/billing/create-subscription',auth,async(req,res)=>{if(!razor)return res.status(503).json({error:'Payments are not configured yet'});const planId=process.env[`RAZORPAY_${String(req.body.plan||'creator').toUpperCase()}_PLAN_ID`];if(!planId)return res.status(400).json({error:'Plan is not configured'});try{const s=await razor.subscriptions.create({plan_id:planId,total_count:1200,quantity:1,customer_notify:true,notes:{email:req.user.email,plan:req.body.plan}});res.json({subscriptionId:s.id,keyId:process.env.RAZORPAY_KEY_ID})}catch(e){res.status(400).json({error:e.error?.description||e.message})}});
app.post('/api/billing/verify',auth,async(req,res)=>{const {razorpay_payment_id,razorpay_subscription_id,razorpay_signature,plan}=req.body;const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${razorpay_payment_id}|${razorpay_subscription_id}`).digest('hex');if(expected!==razorpay_signature)return res.status(400).json({error:'Payment verification failed'});const u=users.get(req.user.email);if(u){u.plan=plan||'creator';users.set(u.email,u)}res.json({ok:true,plan:u?.plan})});
app.post('/api/billing/webhook',(req,res)=>{const sig=req.headers['x-razorpay-signature'];if(process.env.RAZORPAY_WEBHOOK_SECRET){const expected=crypto.createHmac('sha256',process.env.RAZORPAY_WEBHOOK_SECRET).update(JSON.stringify(req.body)).digest('hex');if(sig!==expected)return res.status(401).end()}res.json({received:true})});
function oauth(){return new google.auth.OAuth2(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,process.env.GOOGLE_REDIRECT_URI||`${process.env.PUBLIC_BASE_URL}/api/youtube/callback`)}
app.get('/api/youtube/connect',auth,(req,res)=>{if(!process.env.GOOGLE_CLIENT_ID)return res.status(503).json({error:'YouTube OAuth is not configured'});const state=crypto.randomBytes(24).toString('hex');oauthStates.set(state,req.user.email);const u=oauth();res.redirect(u.generateAuthUrl({access_type:'offline',prompt:'consent',scope:['https://www.googleapis.com/auth/youtube.upload','https://www.googleapis.com/auth/youtube.readonly'],state}))});
app.get('/api/youtube/callback',async(req,res)=>{try{const email=oauthStates.get(req.query.state);if(!email)throw new Error('Invalid OAuth state');oauthStates.delete(req.query.state);const c=oauth(),{tokens}=await c.getToken(req.query.code);const u=users.get(email);if(u){u.youtubeRefreshToken=enc(tokens.refresh_token);users.set(email,u)}res.redirect(`${process.env.FRONTEND_ORIGIN||'https://gowardhan0.github.io'}/?youtube=connected`)}catch(e){res.status(400).send(`YouTube connection failed: ${e.message}`)}});
app.post('/api/youtube/upload',auth,upload.single('video'),async(req,res)=>{const u=users.get(req.user.email);if(!u?.youtubeRefreshToken)return res.status(400).json({error:'Connect YouTube first'});if(!req.file)return res.status(400).json({error:'Video required'});const c=oauth();c.setCredentials({refresh_token:dec(u.youtubeRefreshToken)});const yt=google.youtube({version:'v3',auth:c});try{const r=await yt.videos.insert({part:['snippet','status'],requestBody:{snippet:{title:req.body.title||'ClipForge Short',description:req.body.description||'',tags:String(req.body.tags||'').split(',').filter(Boolean),categoryId:'22'},status:{privacyStatus:req.body.privacyStatus||'private'}},media:{body:(await fs.open(req.file.path,'r')).createReadStream()}});await fs.rm(req.file.path,{force:true});res.json({ok:true,videoId:r.data.id,url:`https://youtube.com/watch?v=${r.data.id}`})}catch(e){res.status(400).json({error:e.message})}});
app.use((err,_req,res,_next)=>res.status(400).json({error:err.message||'Request failed'}));
const port=Number(process.env.PORT||8080);app.listen(port,()=>console.log(`ClipForge API listening on ${port}`));