import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import multer from 'multer';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { v4 as uuid } from 'uuid';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import Razorpay from 'razorpay';
import ffmpegPath from 'ffmpeg-static';
import OpenAI from 'openai';
import pg from 'pg';

const {Pool}=pg, exec=promisify(execFile), __dirname=path.dirname(fileURLToPath(import.meta.url));
const DATA=path.join(__dirname,'data'),UPLOADS=path.join(DATA,'uploads'),OUTPUTS=path.join(DATA,'outputs');
await fs.mkdir(UPLOADS,{recursive:true});await fs.mkdir(OUTPUTS,{recursive:true});
const app=express();
const origins=(process.env.FRONTEND_ORIGIN||'https://gowardhan0.github.io').split(',').map(x=>x.trim());
app.use(cors({origin:(o,cb)=>!o||origins.includes(o)?cb(null,true):cb(new Error('Origin not allowed'))}));
app.use(express.json({limit:'2mb'}));app.use('/media',express.static(DATA));
const upload=multer({dest:UPLOADS,limits:{fileSize:Number(process.env.MAX_UPLOAD_BYTES||2000000000)},fileFilter:(_r,f,cb)=>cb(/^video\/(mp4|quicktime|webm|x-matroska)$/.test(f.mimetype)?null:new Error('Only MP4, MOV, WebM or MKV videos are supported.'))});
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('render.com')?{rejectUnauthorized:false}:undefined}):null;
const jobs=new Map();
const openai=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;
const razor=process.env.RAZORPAY_KEY_ID&&process.env.RAZORPAY_KEY_SECRET?new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET}):null;
const jwtSecret=process.env.JWT_SECRET||'CHANGE_ME_BEFORE_PRODUCTION';
const base=req=>process.env.PUBLIC_BASE_URL||`${req.protocol}://${req.get('host')}`;
const sign=u=>jwt.sign({sub:u.id,email:u.email,role:u.role,plan:u.plan},jwtSecret,{expiresIn:'30d'});
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw 0;req.user=jwt.verify(h.slice(7),jwtSecret);next()}catch{res.status(401).json({error:'Authentication required'})}}
function admin(req,res,next){if(!['owner','admin'].includes(req.user?.role))return res.status(403).json({error:'Admin access required'});next()}
async function q(text,params=[]){if(!pool)throw new Error('DATABASE_URL is not configured');return pool.query(text,params)}
async function userByEmail(email){const r=await q('select * from users where email=$1',[email.toLowerCase()]);return r.rows[0]}
async function userById(id){const r=await q('select * from users where id=$1',[id]);return r.rows[0]}
async function initDb(){if(!pool){console.warn('DATABASE_URL missing: persistent auth is disabled');return}await q(`create table if not exists users(id uuid primary key,email text unique not null,password_hash text not null,role text not null default 'user',plan text not null default 'free',created_at timestamptz not null default now());`);await q(`create table if not exists jobs(id uuid primary key,user_id uuid references users(id) on delete cascade,status text not null,progress int not null default 0,filename text,error text,clips_json jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());`);await seed(process.env.ADMIN_EMAIL,process.env.ADMIN_PASSWORD,'owner','pro');await seed(process.env.AGENCY_EMAIL,process.env.AGENCY_PASSWORD,'user','agency')}
async function seed(email,password,role,plan){if(!email||!password)return;const hash=await bcrypt.hash(password,12);await q(`insert into users(id,email,password_hash,role,plan) values($1,$2,$3,$4,$5) on conflict(email) do update set password_hash=excluded.password_hash,role=excluded.role,plan=excluded.plan`,[uuid(),email.toLowerCase(),hash,role,plan]);console.log(`Seeded ${role}/${plan} account: ${email}`)}
app.get('/api/health',async(_r,res)=>{try{if(pool)await q('select 1');res.json({ok:true,service:'clipforge-api',version:'2.1.0',database:Boolean(pool)})}catch(e){res.status(503).json({ok:false,error:'Database unavailable'})}});
app.get('/api/config',(_r,res)=>res.json({razorpayKeyId:process.env.RAZORPAY_KEY_ID||null,plans:[{id:'creator',name:'Creator',price:19,currency:'USD'},{id:'pro',name:'Pro',price:49,currency:'USD'},{id:'agency',name:'Agency',price:149,currency:'USD'}]}));
app.post('/api/auth/register',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return res.status(400).json({error:'Use a valid email and an 8+ character password'});if(await userByEmail(email))return res.status(409).json({error:'Account already exists'});const u={id:uuid(),email,password_hash:await bcrypt.hash(password,12),role:'user',plan:'free'};await q('insert into users(id,email,password_hash,role,plan) values($1,$2,$3,$4,$5)',[u.id,u.email,u.password_hash,u.role,u.plan]);res.status(201).json({token:sign(u),user:{id:u.id,email:u.email,role:u.role,plan:u.plan}})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),u=await userByEmail(email);if(!u||!(await bcrypt.compare(String(req.body.password||''),u.password_hash)))return res.status(401).json({error:'Invalid email or password'});res.json({token:sign(u),user:{id:u.id,email:u.email,role:u.role,plan:u.plan}})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/me',auth,async(req,res)=>{try{const u=await userById(req.user.sub);if(!u)return res.status(404).json({error:'User not found'});res.json({user:{id:u.id,email:u.email,role:u.role,plan:u.plan}})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/users',auth,admin,async(_req,res)=>{const r=await q('select id,email,role,plan,created_at from users order by created_at desc');res.json({users:r.rows})});
app.get('/api/admin/stats',auth,admin,async(_req,res)=>{const u=await q('select count(*)::int as users from users'),j=await q('select count(*)::int as jobs from jobs');res.json({users:u.rows[0].users,jobs:j.rows[0].jobs})});
app.post('/api/analyze',auth,upload.single('video'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Video file is required'});if(req.body.rightsConfirmed!=='true'){await fs.rm(req.file.path,{force:true});return res.status(400).json({error:'You must confirm ownership or editing permission'})}const id=uuid(),ext=path.extname(req.file.originalname)||'.mp4',source=path.join(UPLOADS,`${id}${ext}`);await fs.rename(req.file.path,source);const job={id,userId:req.user.sub,status:'queued',progress:0,filename:req.file.originalname};jobs.set(id,job);if(pool)await q('insert into jobs(id,user_id,status,progress,filename) values($1,$2,$3,$4,$5)',[id,req.user.sub,'queued',0,req.file.originalname]);res.status(202).json({id,status:'queued'});processJob(id,source,req.body.title||req.file.originalname).catch(e=>console.error('Upload job launch failed',e))}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/analyze-url',auth,async(req,res)=>{try{const sourceUrl=String(req.body.url||'').trim();if(req.body.rightsConfirmed!==true)return res.status(400).json({error:'You must confirm ownership or editing permission'});let u;try{u=new URL(sourceUrl)}catch{return res.status(400).json({error:'Invalid URL.'})}if(!/^https?:$/.test(u.protocol))return res.status(400).json({error:'Enter a valid http(s) video URL.'});if(/(^|\.)youtube\.com$|(^|\.)youtu\.be$|(^|\.)youtube-nocookie\.com$/i.test(u.hostname))return res.status(400).json({error:'YouTube links are not accepted here. For a video you own or are licensed to edit, export the MP4 from YouTube Studio and upload it.'});const r=await fetch(sourceUrl,{redirect:'follow'});if(!r.ok||!r.body)throw new Error('The video URL could not be fetched.');const ct=(r.headers.get('content-type')||'').toLowerCase(),ext=path.extname(u.pathname).toLowerCase();if(!ct.startsWith('video/')&&!['.mp4','.mov','.webm','.mkv'].includes(ext))throw new Error('URL must point directly to a video file (MP4, MOV, WebM or MKV).');const max=Number(process.env.MAX_UPLOAD_BYTES||2000000000),len=Number(r.headers.get('content-length')||0);if(len>max)throw new Error('Video exceeds the 2 GB limit.');const id=uuid(),source=path.join(UPLOADS,id+(['.mp4','.mov','.webm','.mkv'].includes(ext)?ext:'.mp4')),fh=await fs.open(source,'w');let total=0;try{for await(const chunk of r.body){total+=chunk.length;if(total>max)throw new Error('Video exceeds the 2 GB limit.');await fh.write(chunk)}}finally{await fh.close()}const job={id,userId:req.user.sub,status:'queued',progress:0,filename:path.basename(source)};jobs.set(id,job);if(pool)await q('insert into jobs(id,user_id,status,progress,filename) values($1,$2,$3,$4,$5)',[id,req.user.sub,'queued',0,path.basename(source)]);res.status(202).json({id,status:'queued'});processJob(id,source,path.basename(u.pathname)).catch(e=>console.error('URL job launch failed',e));}catch(e){res.status(400).json({error:e.message||'Unable to fetch video URL'})}});
async function getJob(id){if(jobs.has(id))return jobs.get(id);if(!pool)return null;const r=await q('select id,user_id as "userId",status,progress,filename,error,clips_json as clips,created_at as "createdAt",updated_at as "updatedAt" from jobs where id=$1',[id]);return r.rows[0]||null}
async function setJob(id,p){const j={...(jobs.get(id)||{}),...p,updatedAt:new Date().toISOString()};jobs.set(id,j);if(pool)await q(`update jobs set status=$1,progress=$2,error=$3,clips_json=$4,updated_at=now() where id=$5`,[j.status||'processing',j.progress||0,j.error||null,j.clips?JSON.stringify(j.clips):null,id]).catch(()=>{});}
app.get('/api/jobs/:id',auth,async(req,res)=>{const j=await getJob(req.params.id);if(!j)return res.status(404).json({error:'Job not found'});if(j.userId!==req.user.sub&&!['owner','admin'].includes(req.user.role))return res.status(403).json({error:'Not allowed'});res.json(j)});
async function probe(f){try{const {stderr}=await exec(ffmpegPath,['-i',f,'-hide_banner'],{maxBuffer:10000000});const m=stderr.match(/Duration:\s*(\d+):(\d+):(\d+(?:\.\d+)?)/);return {duration:m?Number(m[1])*3600+Number(m[2])*60+Number(m[3]):60}}catch(e){const m=(e.stderr||'').match(/Duration:\s*(\d+):(\d+):(\d+(?:\.\d+)?)/);return {duration:m?Number(m[1])*3600+Number(m[2])*60+Number(m[3]):60}}}
async function transcribe(f){if(!openai)return {text:'',segments:[]};const dir=path.join(DATA,'audio',uuid());await fs.mkdir(dir,{recursive:true});const duration=(await probe(f)).duration,chunkSeconds=480,parts=[];try{for(let start=0;start<duration;start+=chunkSeconds){const out=path.join(dir,'part-'+parts.length+'.mp3'),take=Math.min(chunkSeconds,duration-start);await exec(ffmpegPath,['-y','-ss',String(start),'-i',f,'-t',String(take),'-vn','-ac','1','-ar','16000','-c:a','libmp3lame','-b:a','64k',out],{maxBuffer:20000000});const h=await fs.open(out,'r');let r;try{r=await openai.audio.transcriptions.create({file:h.createReadStream(),model:process.env.WHISPER_MODEL||'whisper-1',response_format:'verbose_json'})}finally{await h.close().catch(()=>{})}for(const seg of (r.segments||[])){const a=Number(seg.start)+start,b=Number(seg.end)+start;if(Number.isFinite(a)&&Number.isFinite(b)&&b>a)parts.push({start:a,end:b,text:String(seg.text||'').trim()})}if(!r.segments?.length&&r.text)parts.push({start,end:start+take,text:String(r.text).trim()})}const segments=parts.filter(x=>x.text).sort((a,b)=>a.start-b.start);return {text:segments.map(x=>'['+x.start.toFixed(1)+'-'+x.end.toFixed(1)+'] '+x.text).join('\n'),segments}}finally{await fs.rm(dir,{recursive:true,force:true}).catch(()=>{})}}
async function choose(timestampedText,duration,title){const fallback=()=>{const out=[];const window=Math.min(45,Math.max(20,duration));for(let i=0;i<Math.min(3,Math.ceil(duration/45));i++){const start=Math.min(Math.max(0,duration-window),i*Math.max(12,window*.65)),end=Math.min(duration,start+window);if(end-start>=12)out.push({start,end,hook:'A key moment from '+(title||'this video'),score:60,title:'Short '+(i+1),description:'AI-selected short-form segment',hashtags:'#shorts #clips'})}return out};if(!openai||!timestampedText.trim())return fallback();try{const r=await openai.chat.completions.create({model:process.env.OPENAI_MODEL||'gpt-4o-mini',temperature:.2,response_format:{type:'json_object'},messages:[{role:'system',content:'You are an expert short-form video editor. Use ONLY timestamps present in the transcript. Never invent timestamps. Find distinct, self-contained clips with strong hooks, useful insights, stories, emotion, humor or memorable statements. Avoid duplicate or heavily overlapping clips.'},{role:'user',content:'Find up to 30 publishable Shorts when the source is long enough. Return JSON {clips:[{start,end,hook,score,title,description,hashtags}]}. Each clip should be 20-60 seconds unless the source is shorter. Use exact timestamp boundaries from the transcript. Rank by score but preserve diversity. Duration '+Math.round(duration)+' seconds. Title: '+title+'. Timestamped transcript:\n'+timestampedText.slice(0,110000)}]});const x=JSON.parse(r.choices?.[0]?.message?.content||'{}'),clips=Array.isArray(x.clips)?x.clips:[],clean=clips.map(c=>({...c,start:Number(c.start),end:Number(c.end),score:Number(c.score)||0})).filter(c=>Number.isFinite(c.start)&&Number.isFinite(c.end)&&c.start>=0&&c.end<=duration&&c.end>c.start&&c.end-c.start>=12&&c.end-c.start<=60).sort((x,y)=>y.score-x.score),picked=[];for(const c of clean){if(!picked.some(p=>Math.max(p.start,c.start)<Math.min(p.end,c.end)))picked.push(c);if(picked.length>=30)break}return picked.length?picked:fallback()}catch(e){console.error('AI clip selection failed:',e.message);return fallback()}}
async function renderShort(input,output,start,end){await exec(ffmpegPath,['-y','-ss',String(start),'-i',input,'-t',String(Math.max(5,end-start)),'-vf',"scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2,setsar=1",'-c:v','libx264','-preset',process.env.FFMPEG_PRESET||'veryfast','-crf','22','-c:a','aac','-b:a','128k','-movflags','+faststart',output],{maxBuffer:20000000})}
async function processJob(id,source,title){try{setJob(id,{status:'processing',progress:5});const m=await probe(source);if(m.duration<12)throw new Error('Video is too short. Please use a video at least 12 seconds long.');setJob(id,{duration:m.duration,progress:15});const t=await transcribe(source);setJob(id,{progress:45});const clips=await choose(t.text||'',m.duration,title);if(!clips.length)throw new Error('No usable moments were found in this video.');const rendered=[];for(let i=0;i<clips.length;i++){const out=path.join(OUTPUTS,id+'-'+(i+1)+'.mp4');await renderShort(source,out,Number(clips[i].start),Number(clips[i].end));rendered.push({...clips[i],url:(process.env.PUBLIC_BASE_URL||'')+'/media/outputs/'+path.basename(out)});setJob(id,{progress:50+Math.round((i+1)/clips.length*48)})}setJob(id,{status:'complete',progress:100,clips:rendered});await fs.rm(source,{force:true}).catch(()=>{})}catch(e){console.error('ClipForge job failed',id,e);await setJob(id,{status:'error',progress:100,error:e.message||'Video processing failed'});await fs.rm(source,{force:true}).catch(()=>{})}}
app.post('/api/billing/create-subscription',auth,async(req,res)=>{if(!razor)return res.status(503).json({error:'Payments are not configured yet'});const planId=process.env[`RAZORPAY_${String(req.body.plan||'creator').toUpperCase()}_PLAN_ID`];if(!planId)return res.status(400).json({error:'Plan is not configured'});try{const s=await razor.subscriptions.create({plan_id:planId,total_count:1200,quantity:1,customer_notify:true,notes:{email:req.user.email,plan:req.body.plan}});res.json({subscriptionId:s.id,keyId:process.env.RAZORPAY_KEY_ID})}catch(e){res.status(400).json({error:e.error?.description||e.message})}});
app.post('/api/billing/verify',auth,async(req,res)=>{const {razorpay_payment_id,razorpay_subscription_id,razorpay_signature,plan}=req.body;const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET||'').update(`${razorpay_payment_id}|${razorpay_subscription_id}`).digest('hex');if(expected!==razorpay_signature)return res.status(400).json({error:'Payment verification failed'});await q('update users set plan=$1 where id=$2',[plan||'creator',req.user.sub]);res.json({ok:true,plan:plan||'creator'})});
app.post('/api/billing/webhook',(req,res)=>{const sig=req.headers['x-razorpay-signature'];if(process.env.RAZORPAY_WEBHOOK_SECRET){const expected=crypto.createHmac('sha256',process.env.RAZORPAY_WEBHOOK_SECRET).update(JSON.stringify(req.body)).digest('hex');if(sig!==expected)return res.status(401).end()}res.json({received:true})});
app.use((err,_req,res,_next)=>res.status(400).json({error:err.message||'Request failed'}));
await initDb();
const port=Number(process.env.PORT||8080);app.listen(port,()=>console.log(`ClipForge API listening on ${port}`));